### ISSUE TITLE
File not present in Qt directory

### ISSUE THREAD

**Issue by SabariSankar** [ddobrev/QtSharp#32]
Hi All,
I installed the setup "qt-opensource-windows-x86-msvc2010_opengl-5.4.1.exe" .But some files/Directory are missing.Detail mentioned in screenshot.
![qtmissingdir](https://cloud.githubusercontent.com/assets/12458725/7665518/7c730bf4-fbd8-11e4-8cee-f0df95f34686.png)

**Comment by ddobrev** [comment]
Please check the README of the project. Qt for MSVC is not only tested, it's not supported at all at present. Only Qt for MinGW has been used during development.

**Comment by grbd** [comment]
The first todo, is just a place holder for using msbuild instead of visual studio at the command line.
The second todo relates to using mono which might hopefully be a future thing.
When I wrote the docs I just wanted to get any build to work since this is all still experimental, so I just focused on using Visual Studio initially.

As ddobrev has said instead  of using the msvc version of Qt instead look for mingw in the Qt downloads section.

**Comment by SabariSankar** [comment]
Hi,
I installed the qt-opensource-windows-x86-mingw491_opengl-5.4.1.exe.And Open command prompt,run the QtSharp.CLI.exe,It needs the path for Qmake and cmake.If i enter any path.then it shows the error.Can you please explain about steps for building.I attached the screenshot for what done by me.Please suggest me what made wrong on that.
![qmake](https://cloud.githubusercontent.com/assets/12458725/7678835/d857ad1a-fd74-11e4-8992-edc84760fd2b.png)

**Comment by SabariSankar** [comment]
Hi All,
I build the QtSharp.CLI app by set the command line such as C:\Qt\Qt5.4.1\5.4\mingw491_32\bin\qmake.exe
C:\Qt\Qt5.4.1\Tools\mingw491_32\bin\mingw32-make.exe on the property Command line arguments.Error comes as "Could not load file or assembly 'CppSharp.Parser.CLI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.".the screenshot is attached below.Can you please tell me any additional configuration made on the project solution.
![vs2010error](https://cloud.githubusercontent.com/assets/12458725/7680411/e640805a-fd83-11e4-9e3f-550d0e414c44.png)

**Comment by ddobrev** [comment]
Do you use a 64-bit Windows? If so, make sure you use AnyCPU and not x86. If not, I am afraid you'll have to recompile CppSharp. The binaries Qt# uses are 64-bit.

**Comment by grbd** [comment]
Looking at the screenshot above, I think QtSharp.CLI is missing a reference to CppSharp.Parser.CLI.dll
There shoud be a Refeferences subdirectory, try adding dll's from there as references to see if that works

**Comment by SabariSankar** [comment]
Hi All,
I am using 32 bit pc.please suggest any solution for this issue.Thanks in advance.

**Comment by ddobrev** [comment]
@SabariSankar I am afraid you have no other choice at the moment except building https://github.com/mono/CppSharp in 32-bit and then using the resulting binaries with Qt#.

**Comment by SabariSankar** [comment]
Can you please explain about How to building the CppSharp in x86.

**Comment by ddobrev** [comment]
@SabariSankar https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md

**Comment by SabariSankar** [comment]
Hi,
I cannot able to understand the link.What is LLVM and Clang?Will I download the both such as LLVM and Clang?Then How to build the CPPSharp.Please suggest me the steps.

**Comment by durswd** [comment]
@SabariSankar 
CppSharp depends on LLVM and Clang, which are  famous libraries.
You need to download the both libraries and compile them.

**Comment by SabariSankar** [comment]
Hi,
Thanks for the explantion.
I have a doubt about LLVM.I need to download all relevent to LLVM.I asked my query on the screen shot.Please suggest me any short 
![llvm](https://cloud.githubusercontent.com/assets/12458725/7704891/a79ac44c-fe5e-11e4-9cfb-39f3cc278c6f.png)
cut idea for downloading LLVM and clong.

**Comment by durswd** [comment]
@SabariSankar 
No. You should use git and subversion on a command line.

For example, you input as follows.

git clone https://github.com/mono/CppSharp.git
svn http://llvm.org/svn/llvm-project/llvm/trunk llvm
cd llvm/tools
svn http://llvm.org/svn/llvm-project/cfe/trunk clang

These are in my private text.
Perhaps it is too old to compile correctly.

**Comment by grbd** [comment]
You might find this helpfull https://github.com/ddobrev/QtSharp/blob/master/Docs/4.%20Building%20-%20CppSharp.md

It's important to match up the correct versions of llvm and clang with cppsharp
usually they update they're documentation over at
https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md

currently llvm = 0e8abfa6ed986c892ec723236e32e78fd9c47b88
clang = 3457cd5516ac741fa106623d9578f5ac88593f4d
for when fetching via git for cppsharp

**Comment by SabariSankar** [comment]
Hi,
Thanks for your help,I tried steps from your description.I used the link  https://github.com/ddobrev/QtSharp/blob/master/Docs/4.%20Building%20-%20CppSharp.md
I downloaded the cppsharp successfully.But failure occure while cloning the LLVM.The error mentioned in the screenshot.Please tell me what will i do for solving this bug.Thanks in advance.
![llvmerror](https://cloud.githubusercontent.com/assets/12458725/7720240/a8011dfc-fee8-11e4-9a9f-596b3413fc33.png)

**Comment by grbd** [comment]
I'd make sure your using the latest version of git
https://git-scm.com/download/win
I think this might have happened to me once with an old version of git on a linux system

**Comment by SabariSankar** [comment]
Hi sorry for the previous message from me.Actually that error due to my antivirus.It blocked something for cloning.I deactivated the antivirus and continued the cloning.Now successfully cloned.

**Comment by SabariSankar** [comment]
Hi I downloaded all files relevent to CppSharp,LLVM and Clang.What will i do the next step?Please tell me.Thanks in advance

**Comment by ddobrev** [comment]
Please continue with the instruction https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md or https://github.com/ddobrev/QtSharp/blob/master/Docs/4.%20Building%20-%20CppSharp.md .

**Comment by SabariSankar** [comment]
Hi,
I did the step such as
cmake -G "Visual Studio 10" -DCLANG_BUILD_EXAMPLES=false -DCLANG_INCLUDE_DOCS=false -DCLANG_INCLUDE_TESTS=false -DCLANG_INCLUDE_DOCS=false -DCLANG_BUILD_EXAMPLES=false -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_EXAMPLES=false -DLLVM_INCLUDE_DOCS=false -DLLVM_INCLUDE_TESTS=false

But cm dprompt shows Configuration incomplete.The screenshot is attached and log also attached.Please suggest.
![cmakeerror](https://cloud.githubusercontent.com/assets/12458725/7722504/97758ffc-fefe-11e4-9baf-ec1da171e897.png)

**Comment by ddobrev** [comment]
It tells you what the error is. You don't have VS 2013. Install it or decrease the version at -G "Visual Studio 10".

**Comment by SabariSankar** [comment]
I entered -G Visual Studio 10.

**Comment by SabariSankar** [comment]
Hi,
I have the visual studio 2010.So what can i do ?I replaced the  -G Visual Studio 12 by  -G Visual Studio 10.Please suggest me .Thanks in advance

**Comment by ddobrev** [comment]
Use the CMake-GUI instead.

**Comment by SabariSankar** [comment]
Sorry instead of which one?

**Comment by grbd** [comment]
Instead of calling cmake at the command line, try using the cmake-gui which is included when you install cmake
or perhaps just install visual studio 2013?

**Comment by SabariSankar** [comment]
If i using the cmake-gui instead of cmake .Opened the CMake application.

**Comment by SabariSankar** [comment]
I have no option for using 2013.Only using 2010 and 2008.cmake-gui instead of cmake .Opened the CMake application atomattically.Still now the LVM.sln file not created.Any idea for solving this issue using visual studio 2010.Please suggest me .

**Comment by ddobrev** [comment]
I remember now we dropped support for VS 2010. Please install VS 2013.

**Comment by SabariSankar** [comment]
Hi,
If I am using VS 2010 means,we wont access the Qt in c#?

**Comment by SabariSankar** [comment]
Now i run the command such as 
cmake -G "Visual Studio 10" -DCLANG_BUILD_EXAMPLES=false -DCLANG_INCLUDE_DOCS=false -DCLANG_INCLUDE_TESTS=false -DCLANG_INCLUDE_DOCS=false -DCLANG_BUILD_EXAMPLES=false -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_EXAMPLES=false -DLLVM_INCLUDE_DOCS=false -DLLVM_INCLUDE_TESTS=false

Now small quantity of error will come.Error mentioned in screenshot
![ff](https://cloud.githubusercontent.com/assets/12458725/7727658/cdeeb256-ff27-11e4-890b-c2493c0292c0.png)

Error saying OCaml is missing.What is Ocaml.If you know means ,Please explain what is and How to install to pc.

**Comment by tritao** [comment]
The screenshot you posted has the answer: `Host Visual Studio must be at least 2013`.

**Comment by SabariSankar** [comment]
Hi,
Thanks for help.Is there any possible way for accessing Qt in c# files(Visual studio 2010).Please suggest me.Thanks in advance.

**Comment by SabariSankar** [comment]
Hi,
Is Visual studio 2012 enough for this.
cmake -G "Visual Studio 10" -DCLANG_BUILD_EXAMPLES=false -DCLANG_INCLUDE_DOCS=false -DCLANG_INCLUDE_TESTS=false -DCLANG_INCLUDE_DOCS=false -DCLANG_BUILD_EXAMPLES=false -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_EXAMPLES=false -DLLVM_INCLUDE_DOCS=false -DLLVM_INCLUDE_TESTS=false
