### ISSUE TITLE
Can't build QtSharp on VS2013 - Missing file: QtModuleInfo.cs

### ISSUE THREAD

**Issue by joce** [ddobrev/QtSharp#38]
I've been trying to build QtSharp following the instruction provided here:
https://github.com/ddobrev/QtSharp/blob/master/Docs/2.%20Running%20-%20QtSharp.CLI.md
However, it would appear that the file QtSharp\QtSharp\QtModuleInfo.cs is missing from the repo.
Or should it come from somewhere else?

**Comment by ddobrev** [comment]
I had actually forgotten to commit it, sorry about that. It's there now.

**Comment by joce** [comment]
Many thanks.
