### ISSUE TITLE
Cannot able to compile with x86 Cpp Sharp dlls

### ISSUE THREAD

**Issue by manikk** [ddobrev/QtSharp#4]
Cannot able to compile with the x86 dlls downloaded from 
https://dl.dropboxusercontent.com/u/194502/CppSharp/CppSharp_VS2012_423_artifacts.zip. The following error occur while building the project. 

1. The type or namespace name 'Attribute' does not exist in the namespace 'CppSharp.AST' (are you missing an assembly reference?)	D:\QtSharp\QtSharp\Documentation.cs	14	32	QtSharp

It would be fine to have the required x86 Cpp Sharp dlls in the References folder.

**Comment by ddobrev** [comment]
C++# now has regular binary 32-bit releases for Windows at https://github.com/mono/CppSharp/releases so this is no longer a problem.
