### ISSUE TITLE
QtShapr for DOTNET Core

### ISSUE THREAD

**Issue by dsoronda** [ddobrev/QtSharp#47]
Is it hard to add support for .NET Core ?

I could easily switch QtSharpDemo to .NET4.5/.NET4.6.1/Core builds and maybe we could have it run on Linux/OS x ?

**Comment by ddobrev** [comment]
.NET Core and Mono support are different things. QtSharp would have no problem to run on Linux or OS X, I just need to generate the bindings for those OS-es. If you are done with the examples and cross platform support is your next goal, please add issues for OS X and Linux bindings.
