### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by ShalokShalom** [ddobrev/QtSharp#67]
Your README speaks less about the current state of the project. 

On the homepage of MonoDevelop is QtSharp very underrepresented currently, without any screenshot and described as "Still in early development."

Is this still true?

**Comment by ddobrev** [comment]
@ShalokShalom Qt# is already in beta, you can find links to the releases and examples in the README. The only major missing piece is template classes and members which I have almost completed.

**Comment by ShalokShalom** [comment]
And so far as I get this .Net framework thing, is it possible to use C# in order to call QML in order to embed it into a F# project, yes?

**Comment by ddobrev** [comment]
@ShalokShalom Support for QML needs work on its own so that QML code can affect C# and vice versa (just as it is with C++ and QML). I hope to be able to complete this feature by the end of the year if we're talking about my free time.

**Comment by ShalokShalom** [comment]
I mean: Is it the possible to use Qt/QML with F#? Simply by calling it through C#?
.Net compiles all down to CIL?

**Comment by ddobrev** [comment]
If Qt# worked with QML, using it with F# would've been possible too, yes.

**Comment by ShalokShalom** [comment]
By calling it with C# or F# directly?

**Comment by ShalokShalom** [comment]
Cuz your documentation speaks about C# only. Might be nice to change this, if it applies to all languages of the .Net platform. :+1: 

> This project aims to create Mono/.NET libraries that wrap Qt (https://qt-project.org/) thus enabling its usage through C#

**Comment by ddobrev** [comment]
@ShalokShalom your suggestion makes perfect sense. Could you please send a pull request with the change?

**Comment by ddobrev** [comment]
When C# code is compiled, it turns into Microsoft's intermediate language which can be used by any .NET language. So yes, you can use Qt# with F#.
You cannot use QML with F# yet for the same reason you cannot use it with C# - it's a feature not implemented yet.

**Comment by ShalokShalom** [comment]
Yeah, as i thought.

**Comment by ShalokShalom** [comment]
"For now, Qt MinGW for Windows has been the only tested version. Qt for OS X and Linux are planned, Qt for VC++ has not been planned for now."

Is this also still the case?

**Comment by ShalokShalom** [comment]
The Atomic Game engine is currently shifting in its course, since the ~~current~~ previous maintainer is left. Qt/KDE is a possible solution for their UI, QtSharp can be an important role in this concept then.

**Comment by ddobrev** [comment]
@ShalokShalom I haven't stopped working, it's just there's quite some more to do. I need to finish the templates first and then I'll spare time on proper Unix support.

**Comment by ShalokShalom** [comment]
Thanks a lot.

**Comment by ShalokShalom** [comment]
Well, I just found out, that the imperative and object oriented code in  F-Sharp looks and works exactly like in C# - this means, so far as I am concerned, that you could easily port your QtSharp onto F#, so we can use inline there?

**Comment by ddobrev** [comment]
C# produces regular .NET code which can be consumed by any .NET language, F# included.

**Comment by ShalokShalom** [comment]
Yes. the thing is, that you use C# to call the Qt functions, yes?

**Comment by ShalokShalom** [comment]
Do you mean it makes less difference, if the file is called .cs or .fs?

Do be honest: I have less idea, how a sophisticated app will look, is there much C# specific code too write, in order to call Qt?

**Comment by ddobrev** [comment]
When Qt# is compiled, you just add references to it from your F# code and work. That's it.

**Comment by ShalokShalom** [comment]
Ok, thanks. :)

**Comment by pauldotknopf** [comment]
If you need Qml integration, I am working on a project that does exactly this. I'd consider it usable for production.

https://github.com/pauldotknopf/net-core-qml

**Comment by ShalokShalom** [comment]
Oh, no F# API, so I prefer Fable for QML development. Thanks anyway, maybe someone writes an API sometimes.

**Comment by pauldotknopf** [comment]
I'm not sure what Fable is. Care to explain quickly?

**Comment by pauldotknopf** [comment]
Sure, you can translate F# (or even C#) to JS, but you can't use .NET.

With the project I shared, you can use the full .NET runtime. I'm not sure you'd actually want to transpile Qml javascript, since they have unique (and useful) syntax for signals/etc.

**Comment by ShalokShalom** [comment]
With the project you shared, there is no F-Sharp implementation. I am a functional programmer by heart.

**Comment by pauldotknopf** [comment]
Why would you even want to use F# with Qt (which is inherently object oriented)?

Also, Qml.Net is a .NET library, which is reference-able from F# (.NET).

But again, you'd be working against the grain because Qt (and C++) is inherently/fundamentally object-oriented.

Having this "F# implementation" isn't practical, nor does it even make sense.

**Comment by ShalokShalom** [comment]
QML is declarative

**Comment by pauldotknopf** [comment]
To an extent it is, in that you can define the initial object hierarchy declaratively, but beyond that it is entirely object-oriented, not even close to functional.

Something tells me that you don't even know what *you're* looking for.

Good luck with that.

**Comment by ShalokShalom** [comment]
I can even draw QML
