### ISSUE TITLE
KDE support

### ISSUE THREAD

**Issue by ShalokShalom** [ddobrev/QtSharp#72]
So far as I understand, is KDE Tier 1 support already possible?

https://api.kde.org/frameworks/

**Comment by ddobrev** [comment]
QtSharp only binds Qt. Those other libraries would require their own bindings so it's a job for CppSharp rather than QtSharp.

**Comment by ShalokShalom** [comment]
Somebody else who writes Qt Bindings, means that Tier 1 is supported, since they use only Qt libraries as dependencies.

**Comment by ddobrev** [comment]
I understand but separate bindings for each library are needed in addition. Tier 1 consists of far more than just Qt as visible in the table at the link you've shared.

**Comment by ddobrev** [comment]
@ShalokShalom I am not saying it won't work. I am saying it belongs to a separate binding, not to QtSharp.

**Comment by ShalokShalom** [comment]
Ah ok. This was, what I thought from the starts. Seems there was a misunderstanding between this guy and me. Thanks a lot for clearing this up. Good work dude, thanks a lot for it too.
